import path from "node:path";
import fs from "fs-extra";
import kleur from "kleur";
import { detect } from "../detect/index.js";
import {
  CLAUDE_CODE_MIN_VERSION,
  SCHEMA_VERSIONS,
  type InstallJson,
  type StackDetection,
} from "../types/shared.js";
import { projectPaths, templatesDir } from "../util/paths.js";
import { Writer, type WriteRecord } from "./writer.js";

export interface InstallOptions {
  root: string;
  dryRun: boolean;
  force: boolean;
  yes: boolean;
  apexVersion: string;
  sourceChannel?: InstallJson["source_channel"];
  sourceCommand?: string;
}

export interface InstallResult {
  detection: StackDetection;
  records: WriteRecord[];
  installJson: InstallJson;
  hookCount: number;
}

const HOOK_SCRIPTS = [
  "on-session-start.sh",
  "on-prompt-submit.sh",
  "on-post-tool.sh",
  "on-post-tool-failure.sh",
  "on-pre-compact.sh",
  "on-session-end.sh",
];

const SKILL_TEMPLATES = ["apex-recall", "apex-reflect", "apex-review"];
const AGENT_TEMPLATES = ["apex-reflector", "apex-curator", "apex-archaeologist"];

const RULE_TEMPLATES = ["10-conventions.md", "20-gotchas.md"];

const COMMAND_TEMPLATES = ["apex-thumbs-up.md", "apex-thumbs-down.md"];

function applyVars(content: string, vars: Record<string, string>): string {
  return content.replace(/\{\{\s*([A-Z_]+)\s*\}\}/g, (_m, key: string) => {
    return Object.prototype.hasOwnProperty.call(vars, key) ? vars[key]! : `{{${key}}}`;
  });
}

async function readTemplate(name: string): Promise<string | null> {
  const p = path.join(templatesDir(), name);
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return null;
  }
}

function stripManagedWrapper(body: string): string {
  // If the template ships with its own <!-- apex:begin --> / <!-- apex:end -->
  // wrapper, strip it so writeMarkdownManaged doesn't double-wrap.
  return body
    .replace(/^\s*<!--\s*apex:begin\s*-->\s*\n?/, "")
    .replace(/\n?<!--\s*apex:end\s*-->\s*$/, "");
}

function buildVars(
  detection: StackDetection,
  apexVersion: string,
  installDate: string,
): Record<string, string> {
  const langLabel = detection.hasTypeScript && detection.language === "node"
    ? "Node / TypeScript"
    : detection.language;
  return {
    STACK_LANGUAGE: langLabel,
    STACK_FRAMEWORKS: detection.frameworks.join(", ") || "(none detected)",
    STACK_PACKAGE_MANAGER: detection.packageManager ?? "(none detected)",
    STACK_TEST_RUNNER: detection.testRunner ?? "(none detected)",
    STACK_LINT: detection.lint.join(", ") || "(none detected)",
    STACK_FORMAT: detection.format.join(", ") || "(none detected)",
    STACK_CI: detection.ci.join(", ") || "(none detected)",
    APEX_VERSION: apexVersion,
    INSTALL_DATE: installDate,
  };
}

function fallbackStackRule(
  detection: StackDetection,
  vars: Record<string, string>,
): string {
  return [
    "# Stack",
    "",
    `<!-- generated by apex on ${vars["INSTALL_DATE"]} -->`,
    "",
    `- Language: ${vars["STACK_LANGUAGE"]}`,
    `- Frameworks: ${vars["STACK_FRAMEWORKS"]}`,
    `- Package manager: ${vars["STACK_PACKAGE_MANAGER"]}`,
    `- Test runner: ${vars["STACK_TEST_RUNNER"]}`,
    `- Lint: ${vars["STACK_LINT"]}`,
    `- Format: ${vars["STACK_FORMAT"]}`,
    `- CI: ${vars["STACK_CI"]}`,
    "",
    "_Edit this file to add stack-specific rules. APEX will not overwrite your edits unless you run `apex upgrade --force`._",
    "",
    `<!-- raw signals: ${JSON.stringify(detection.rawSignals)} -->`,
    "",
  ].join("\n");
}

function fallbackClaudeMdManaged(vars: Record<string, string>): string {
  return [
    "## Project Stack (managed by APEX)",
    "",
    `- Language: ${vars["STACK_LANGUAGE"]}`,
    `- Frameworks: ${vars["STACK_FRAMEWORKS"]}`,
    `- Package manager: ${vars["STACK_PACKAGE_MANAGER"]}`,
    `- Test runner: ${vars["STACK_TEST_RUNNER"]}`,
    "",
    "## Imports",
    "",
    "@.claude/rules/00-stack.md",
    "@.claude/rules/10-conventions.md",
    "@.claude/rules/20-gotchas.md",
    "",
    `_APEX v${vars["APEX_VERSION"]} — installed ${vars["INSTALL_DATE"]}._`,
  ].join("\n");
}

function fallbackConfigToml(vars: Record<string, string>): string {
  return [
    `# .apex/config.toml — written by apex init on ${vars["INSTALL_DATE"]}`,
    `version = ${SCHEMA_VERSIONS.config}`,
    "",
    "[reflection]",
    "auto_merge = true",
    "min_observations = 2",
    "",
    "[recall]",
    "top_n = 5",
    "max_tokens = 2048",
    "",
    "[redactor]",
    "mode = \"block\"",
    "",
  ].join("\n");
}

function fallbackApexGitignore(): string {
  return [
    "# Managed by APEX — gitignored APEX subtrees",
    "episodes/",
    "index/",
    "metrics/",
    ".staging/",
    "audit.log",
    "",
  ].join("\n");
}

function fallbackHook(name: string): string {
  const event = name.replace(/^on-|\.sh$/g, "");
  return [
    "#!/usr/bin/env bash",
    `# apex-managed hook: ${event}`,
    "# token: apex-hook-v1",
    "set -euo pipefail",
    "EPISODE_ID=\"${APEX_EPISODE_ID:-$(date +%Y-%m-%d-%H%M)}\"",
    "PROJECT_DIR=\"${CLAUDE_PROJECT_DIR:-$(pwd)}\"",
    "mkdir -p \"$PROJECT_DIR/.apex/episodes/$EPISODE_ID\"",
    `echo "{\\"event\\":\\"${event}\\",\\"ts\\":\\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\\"}" \\`,
    `  >> "$PROJECT_DIR/.apex/episodes/$EPISODE_ID/${event}.jsonl" || true`,
    "exit 0",
    "",
  ].join("\n");
}

function fallbackSkillStub(name: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: APEX ${name} skill (stub — replaced on upgrade)`,
    "apex_skill_format: 1",
    "---",
    "",
    `# ${name}`,
    "",
    "Stub installed by apex init. Replaced by the templates package on upgrade.",
    "",
  ].join("\n");
}

function fallbackAgentStub(name: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: APEX ${name} agent (stub — replaced on upgrade)`,
    "tools: []",
    "apex_agent_format: 1",
    "---",
    "",
    `# ${name}`,
    "",
    "Stub installed by apex init. Replaced by the templates package on upgrade.",
    "",
  ].join("\n");
}

function fallbackRuleStub(name: string): string {
  const title = name.replace(/^\d+-/, "").replace(/\.md$/, "");
  return [
    `# ${title}`,
    "",
    "Stub installed by apex init. The reflector and curator subagents will populate this.",
    "",
  ].join("\n");
}

function buildHookEntries(): Record<string, unknown[]> {
  const mk = (event: string, script: string, matcher?: string): unknown => ({
    matcher: matcher ?? "",
    hooks: [
      {
        type: "command",
        command: `bash $CLAUDE_PROJECT_DIR/.claude/hooks/${script}`,
        timeout: 1000,
      },
    ],
  });
  return {
    SessionStart: [mk("SessionStart", "on-session-start.sh")],
    UserPromptSubmit: [mk("UserPromptSubmit", "on-prompt-submit.sh")],
    PostToolUse: [mk("PostToolUse", "on-post-tool.sh", "Bash")],
    PostToolUseFailure: [mk("PostToolUseFailure", "on-post-tool-failure.sh")],
    PreCompact: [mk("PreCompact", "on-pre-compact.sh")],
    SessionEnd: [mk("SessionEnd", "on-session-end.sh")],
  };
}

export async function isInstalled(root: string): Promise<boolean> {
  return fs.pathExists(projectPaths(root).installJson);
}

export async function readInstallJson(root: string): Promise<InstallJson | null> {
  const p = projectPaths(root).installJson;
  if (!(await fs.pathExists(p))) return null;
  return (await fs.readJson(p).catch(() => null)) as InstallJson | null;
}

export async function runInstall(opts: InstallOptions): Promise<InstallResult> {
  const paths = projectPaths(opts.root);
  const writer = new Writer({ dryRun: opts.dryRun });
  const detection = await detect(opts.root);
  const installDate = new Date().toISOString();
  const vars = buildVars(detection, opts.apexVersion, installDate);

  // Ensure base dirs (skipped in dry-run).
  await writer.ensureDir(paths.apexDir);
  await writer.ensureDir(paths.knowledgeDir);
  for (const sub of ["decisions", "patterns", "gotchas", "conventions"]) {
    await writer.ensureDir(path.join(paths.knowledgeDir, sub));
  }
  await writer.ensureDir(paths.proposedDir);
  await writer.ensureDir(paths.episodesDir);
  await writer.ensureDir(paths.indexDir);
  await writer.ensureDir(paths.metricsDir);
  await writer.ensureDir(paths.claudeDir);
  await writer.ensureDir(paths.rulesDir);
  await writer.ensureDir(paths.skillsDir);
  await writer.ensureDir(paths.agentsDir);
  await writer.ensureDir(paths.hooksDir);
  await writer.ensureDir(paths.commandsDir);

  // CLAUDE.md (managed section). Template at templates/CLAUDE.md.tmpl from
  // the scaffold workstream; falls back to inline stub if not yet shipped.
  // The template ships with its own outer apex:begin/end markers for human
  // readability — strip them so writeMarkdownManaged doesn't double-wrap.
  const claudeMdTpl = await readTemplate("CLAUDE.md.tmpl");
  const claudeManagedBody = claudeMdTpl
    ? stripManagedWrapper(applyVars(claudeMdTpl, vars))
    : fallbackClaudeMdManaged(vars);
  await writer.writeMarkdownManaged(paths.claudeMd, claudeManagedBody);

  // CLAUDE.local.md (user-only, written once).
  await writer.writeUserOnce(paths.claudeLocalMd, "");

  // Rules: 00-stack.md is templated and fully apex-owned; 10/20 are static stubs.
  const stackTpl = await readTemplate("claude/rules/00-stack.md.tmpl");
  const stackContent = stackTpl ? applyVars(stackTpl, vars) : fallbackStackRule(detection, vars);
  await writer.writeOwned(path.join(paths.rulesDir, "00-stack.md"), stackContent);

  for (const rule of RULE_TEMPLATES) {
    const tpl = await readTemplate(`claude/rules/${rule}`);
    const content = tpl ? applyVars(tpl, vars) : fallbackRuleStub(rule);
    await writer.writeOwned(path.join(paths.rulesDir, rule), content);
  }

  // Skills.
  for (const skill of SKILL_TEMPLATES) {
    const tpl = await readTemplate(`claude/skills/${skill}/SKILL.md`);
    const dest = path.join(paths.skillsDir, skill, "SKILL.md");
    if (tpl) {
      await writer.writeOwned(dest, applyVars(tpl, vars));
    } else {
      writer.recordSkippedTemplate(dest, `${skill}/SKILL.md`);
      await writer.writeOwned(dest, fallbackSkillStub(skill));
    }
  }

  // Agents.
  for (const agent of AGENT_TEMPLATES) {
    const tpl = await readTemplate(`claude/agents/${agent}.md`);
    const dest = path.join(paths.agentsDir, `${agent}.md`);
    if (tpl) {
      await writer.writeOwned(dest, applyVars(tpl, vars));
    } else {
      writer.recordSkippedTemplate(dest, `${agent}.md`);
      await writer.writeOwned(dest, fallbackAgentStub(agent));
    }
  }

  // Slash commands (Phase 2 §2.5 feedback). Templates ship as plain markdown
  // files; missing templates skip silently rather than producing a stub.
  for (const cmd of COMMAND_TEMPLATES) {
    const tpl = await readTemplate(`claude/commands/${cmd}`);
    if (!tpl) continue;
    const dest = path.join(paths.commandsDir, cmd);
    await writer.writeOwned(dest, applyVars(tpl, vars));
  }

  // Hooks.
  for (const hook of HOOK_SCRIPTS) {
    const tpl = await readTemplate(`claude/hooks/${hook}`);
    const dest = path.join(paths.hooksDir, hook);
    const content = tpl ? applyVars(tpl, vars) : fallbackHook(hook);
    await writer.writeOwned(dest, content, { dryRun: opts.dryRun, executable: true });
  }

  // settings.json with managed hooks block.
  await writer.writeSettingsHooks(paths.settingsJson, buildHookEntries());

  // .apex/install.json — APEX owned, always rewritten.
  const prior = await readInstallJson(opts.root);
  const installJson: InstallJson = {
    apex_version: opts.apexVersion,
    installed_at: prior?.installed_at ?? installDate,
    last_upgraded_at: installDate,
    source_channel: opts.sourceChannel ?? prior?.source_channel ?? "local",
    source_command: opts.sourceCommand ?? prior?.source_command ?? "apex init",
    schema_versions: { ...SCHEMA_VERSIONS },
    claude_code_min_version: CLAUDE_CODE_MIN_VERSION,
  };
  await writer.writeOwned(paths.installJson, `${JSON.stringify(installJson, null, 2)}\n`);

  // .apex/config.toml — user-owned (write once).
  const configTpl = await readTemplate(".apex/config.toml.tpl");
  const configContent = configTpl ? applyVars(configTpl, vars) : fallbackConfigToml(vars);
  await writer.writeUserOnce(paths.configToml, configContent);

  // .apex/.gitignore — APEX-owned, replaced on upgrade.
  await writer.writeOwned(paths.apexGitignore, fallbackApexGitignore());

  // Root .gitignore — managed block.
  await writer.writeGitignoreManaged(paths.rootGitignore, [
    "CLAUDE.local.md",
    ".apex/episodes/",
    ".apex/index/",
    ".apex/metrics/",
    ".apex/.staging/",
    ".apex/audit.log",
  ]);

  // Stub knowledge convention "_pending-stack.md" referenced by spec §7.
  const pendingStack = path.join(paths.knowledgeDir, "conventions", "_pending-stack.md");
  await writer.writeUserOnce(
    pendingStack,
    [
      "---",
      "id: pending-stack",
      "type: convention",
      "title: Detected stack (pending review)",
      "applies_to: all",
      "confidence: medium",
      "sources:",
      "  - kind: bootstrap",
      `    ref: apex-init/${installDate}`,
      `created: ${installDate.slice(0, 10)}`,
      `last_validated: ${installDate.slice(0, 10)}`,
      "tags: [stack, bootstrap]",
      "---",
      "",
      `Detected stack on \`apex init\`:`,
      "",
      `- Language: ${vars["STACK_LANGUAGE"]}`,
      `- Frameworks: ${vars["STACK_FRAMEWORKS"]}`,
      `- Package manager: ${vars["STACK_PACKAGE_MANAGER"]}`,
      `- Test runner: ${vars["STACK_TEST_RUNNER"]}`,
      `- Lint: ${vars["STACK_LINT"]}`,
      `- CI: ${vars["STACK_CI"]}`,
      "",
      "Review and either delete this file or move it (renamed) into `.apex/knowledge/conventions/`.",
      "",
    ].join("\n"),
  );

  return {
    detection,
    records: writer.records,
    installJson,
    hookCount: Object.keys(buildHookEntries()).length,
  };
}

export function formatStatsBanner(result: InstallResult, proposedCount = 0): string {
  const d = result.detection;
  const stackParts: string[] = [];
  if (d.language !== "unknown") stackParts.push(d.language);
  if (d.hasTypeScript && d.language === "node") stackParts.push("TypeScript");
  stackParts.push(...d.frameworks);
  if (d.packageManager) stackParts.push(d.packageManager);
  if (d.testRunner) stackParts.push(d.testRunner);
  stackParts.push(...d.lint);
  stackParts.push(...d.ci);

  const stack = stackParts.length > 0 ? stackParts.join(" / ") : "unknown stack";
  const proposedLine = proposedCount > 0
    ? `  knowledge:    ${proposedCount} proposals in .apex/proposed/ (review with \`apex review\`)`
    : `  knowledge:    0 entries (archaeologist found no signals to bootstrap)`;
  return [
    kleur.green().bold("APEX installed."),
    `  stack:        ${stack}`,
    `  hooks:        ${result.hookCount} installed in .claude/settings.json`,
    proposedLine,
    `  next session: APEX will load at SessionStart automatically.`,
    "",
    `Run ${kleur.bold("apex status")} for details. ${kleur.bold("apex uninstall")} removes everything.`,
    "",
  ].join("\n");
}
