// Renders the human-readable curation summary markdown.

import type { DedupedCluster } from "./dedupe.js";
import type { StaleEntry } from "./stale.js";
import type { DriftEntry } from "./drift.js";

export interface SummaryData {
  date: string;
  duplicateClusters: DedupedCluster[];
  staleEntries: StaleEntry[];
  driftEntries: DriftEntry[];
  mergeProposals: string[];
}

function section(title: string, lines: string[]): string {
  const header = `## ${title}`;
  if (lines.length === 0) {
    return `${header}\n\nNone.\n`;
  }
  return `${header}\n\n${lines.join("\n")}\n`;
}

export function renderSummary(data: SummaryData): string {
  const parts: string[] = [];

  parts.push(`# APEX Curation Report — ${data.date}`);
  parts.push("");
  parts.push(`Generated by \`apex curate\`. Re-run on the same day overwrites this file.`);
  parts.push("");

  // ---- Duplicate clusters ---------------------------------------------------
  const dupLines: string[] = [];
  for (const cluster of data.duplicateClusters) {
    const { pair, proposeMerge, keepId, discardId } = cluster;
    const score = (pair.score * 100).toFixed(1);
    const label = proposeMerge
      ? `MERGE PROPOSED: keep \`${keepId}\`, discard \`${discardId}\``
      : `DUPLICATE CLUSTER: \`${pair.a.frontmatter.id}\` ↔ \`${pair.b.frontmatter.id}\``;
    dupLines.push(
      `- **${label}**  ` +
        `(${pair.via} similarity ${score}%, type: ${pair.a.frontmatter.type})`,
    );
    if (proposeMerge && data.mergeProposals.length > 0) {
      const proposal = data.mergeProposals.find((p) =>
        p.includes(`_merge-${discardId}-into-${keepId}`),
      );
      if (proposal) {
        dupLines.push(`  Proposal written to: \`${proposal}\``);
      }
    }
  }
  parts.push(section("Duplicate clusters", dupLines));

  // ---- Stale entries --------------------------------------------------------
  const staleLines: string[] = [];
  for (const s of data.staleEntries) {
    staleLines.push(
      `- \`${s.entry.frontmatter.id}\` (${s.entry.frontmatter.type}) — ` +
        `last validated ${s.lastValidated} (${s.daysSinceValidated}d ago). ` +
        `Hint: set \`verified: false\` and re-review.`,
    );
  }
  parts.push(section("Stale entries", staleLines));

  // ---- Drift candidates -----------------------------------------------------
  const driftLines: string[] = [];
  for (const d of data.driftEntries) {
    driftLines.push(
      `- \`${d.entry.frontmatter.id}\` — source ref \`${d.ref}\` points to ` +
        `\`${d.missingPath}\` which no longer exists. Review and update entry.`,
    );
  }
  parts.push(section("Drift candidates", driftLines));

  // ---- Tally ----------------------------------------------------------------
  parts.push("## Tally");
  parts.push("");
  parts.push(`| Metric | Count |`);
  parts.push(`|---|---|`);
  parts.push(`| Duplicate clusters | ${data.duplicateClusters.length} |`);
  parts.push(
    `| Merge proposals written | ${data.mergeProposals.length} |`,
  );
  parts.push(`| Stale entries | ${data.staleEntries.length} |`);
  parts.push(`| Drift candidates | ${data.driftEntries.length} |`);
  parts.push("");

  return parts.join("\n");
}
